[build]
  base    = ""
  command = "yarn netlify_build_stage"
  publish = "/build"

[context.production]
  command = "yarn netlify_build_stage"

[context.staging]
  command = "yarn netlify_build_stage"


  