[build]
  base    = ""
  command = "yarn netlify_build_stage"
  publish = "/build"

[context.production]
  command = "yarn netlify_build_stage"

[context.staging]
  command = "yarn netlify_build_stage"

[[redirects]]
  from = "*"
  to = "/index.html"

  # The default HTTP status code is 301, but you can define a different one.
  status = 200  


  